version: '3'

services:
  mongo:
    container_name: mongodb
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'devbills' # se eu passar com "-" o yml entende que é um array
      MONGO_INITDB_ROOT_PASSWORD: 'pass123'
    ports:
      - '27017:27017'
    networks:
      - local

  app:
    depends_on:
      - mongo
    container_name: devbills-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/app
    ports:
      - '5555:5555'
    environment:
      MONGO_URL: 'mongodb://devbills:pass123@mongodb:27017/devbills?authSource=admin'
      
    networks:
      - local

networks:
  local:
    name: local